export const MyDimesions = {
  kPaddingSmall: 12,
  kPaddingMedium: 16,
  kPaddingLarge: 20,
  kLogoSize: 34,
  kBannerSize: 40,
  kIconLarge: 30,
  kIconMedium: 24,
  kLabelSmall: 18,
  kLabelMedium: 20,
  kLabelLarge: 22,
  kBodySmall: 14,
  kBodyMedium: 16,
  kBodyLarge: 18,
  kCartNumber: 10,
};
